CREATE TABLE "api_keys" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"key_type" text NOT NULL,
	"key_hash" text NOT NULL,
	"key_prefix" text NOT NULL,
	"key_last4" text NOT NULL,
	"revoked" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "api_keys_key_hash_key" UNIQUE("key_hash"),
	CONSTRAINT "api_keys_key_type_check" CHECK ("api_keys"."key_type" IN ('publishable', 'secret'))
);
--> statement-breakpoint
CREATE TABLE "dashboard_memberships" (
	"workos_user_id" text NOT NULL,
	"tenant_id" uuid NOT NULL,
	"role" text NOT NULL,
	"email" text,
	"workos_organization_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "dashboard_memberships_workos_user_id_tenant_id_pk" PRIMARY KEY("workos_user_id","tenant_id"),
	CONSTRAINT "dashboard_memberships_role_check" CHECK ("dashboard_memberships"."role" IN ('tenant_admin', 'super_admin'))
);
--> statement-breakpoint
CREATE TABLE "tenant_skills" (
	"tenant_id" uuid NOT NULL,
	"skill_id" text NOT NULL,
	"content" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tenant_skills_tenant_id_skill_id_pk" PRIMARY KEY("tenant_id","skill_id")
);
--> statement-breakpoint
CREATE TABLE "tenants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"allowed_origins" text[] DEFAULT '{}'::text[] NOT NULL,
	"allowed_app_ids" text[] DEFAULT '{}'::text[] NOT NULL,
	"usage_cap_seconds" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "usage_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "usage_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"seconds" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "api_keys" ADD CONSTRAINT "api_keys_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboard_memberships" ADD CONSTRAINT "dashboard_memberships_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tenant_skills" ADD CONSTRAINT "tenant_skills_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "usage_events" ADD CONSTRAINT "usage_events_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "api_keys_tenant_idx" ON "api_keys" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "dashboard_memberships_user_idx" ON "dashboard_memberships" USING btree ("workos_user_id");--> statement-breakpoint
CREATE INDEX "dashboard_memberships_org_idx" ON "dashboard_memberships" USING btree ("workos_organization_id");--> statement-breakpoint
CREATE INDEX "usage_events_tenant_time_idx" ON "usage_events" USING btree ("tenant_id","created_at");