CREATE TABLE "mac_entitlements" (
  "user_id" text PRIMARY KEY NOT NULL,
  "email" text,
  "status" text DEFAULT 'none' NOT NULL,
  "period_start" text,
  "period_end" text,
  "plan" text,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mac_usage_events" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" text NOT NULL,
  "email" text NOT NULL,
  "seconds" integer DEFAULT 0 NOT NULL,
  "result" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "mac_usage_events_user_time_idx" ON "mac_usage_events" USING btree ("user_id","created_at");
